/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Character(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Revamp/mixamo.glb')
  const { actions } = useAnimations(animations, group)

  const scroll = useScroll()

  useLayoutEffect(() => {
        const action = actions['Action']; 
        if (action) {
          action.play();
          action.paused = true;
        }
    }, [actions]);
  
    useFrame(() => {
         
        const scrollOffset = scroll.offset
        
        // Update camera animation
        if (actions && actions['Action']) {
          const action = actions['Action'];
          const duration = action.getClip().duration;
          // Map the scroll progress to animation time
          action.time = scrollOffset * duration;
        }
    });





  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[0, 0, 54.829]}
          rotation={[Math.PI / 2, 0, 3.142]}
          scale={0.01}>
          <skinnedMesh
            name="Beta_Joints"
            geometry={nodes.Beta_Joints.geometry}
            material={materials['Beta_Joints_MAT1.002']}
            skeleton={nodes.Beta_Joints.skeleton}
          />
          <skinnedMesh
            name="Beta_Surface"
            geometry={nodes.Beta_Surface.geometry}
            material={materials['Beta_HighLimbsGeoSG3.002']}
            skeleton={nodes.Beta_Surface.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Revamp/mixamo.glb')
